
name: roll-video Docker Build and Push

on:
  push:
    paths:
      - '.github/workflows/roll-video-build.yml'
      - 'app/services/roll_video/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'yinshiyionly/NewRollVideo' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: app/services/roll_video
          file: app/services/roll_video/Dockerfile
          push: true
          tags: |
            catchoco/roll-video:new-supervisor
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
